services:
  db:
      image: postgres:15.5-alpine
      container_name: database-container
      env_file:
        - .env
      environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: ${DB_PASSWORD}
      volumes:
        - postgres-data:/var/lib/postgresql/data
      restart: always

  django:
    image: django-container
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=True
      - DJANGO_LOG_LEVEL=DEBUG
      - DB_PASSWORD=postgres
      - DATABASE_DB=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - ALLOWED_HOSTS=["localhost", "127.0.0.1"]
    container_name: django-container
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always

volumes:
  postgres-data:
